apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydeployment1
 labels:
  app: labelofmydeployment
spec:
 replicas: 6
 selector:
  matchLabels:
   app: myapp1
 template:
  metadata:
   name: mypod1
   labels:
    app: myapp1
  spec:
   containers:
   - name: mycontainer1
     image: eglitmyk/demoappclinic
     ports:
     - containerPort: 80