
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  labels:
    app: frontendapp
spec:
  selector:
    matchLabels:
      app: frontendapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql"
        - name: WORDPRESS_DB_PASSWORD
          value: "dbpassword11"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_NAME
          value: "webappdb"
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: azure-managed-disk-frontendpvc



