apiVersion: v1
kind: Service
metadata:
  name: frontendapplbservice
  labels:
    app: frontendapp
spec:
  type: LoadBalancer
  selector:
    app: frontendapp
  ports:
  - port: 80
    targetPort: 80
