apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 3
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app-cont
        image: eglitmyk/myappimage
        ports:
        - name: http
          containerPort: 80
