apiVersion: v1
kind: Service
metadata:
 name: frontendlbservice
 labels: 
  app: frontend-app 
spec:
   type: LoadBalancer
   selector:
     app: frontend-app
   ports:
    - name: http
      port: 80
      targetPort: 80